Added arm_id variable to use moveit for multiple panda arms
ros-planning/panda_moveit_config pull request #104
Opened 2022-03-18 15:21 UTC by Xiaoyu27

Hi Moveit group,

Please check the modification I made on the panda_moveit_config. I added the "arm_id" to the files. Now each panda arm can has its own move_group. It is possible to add multiple panda arms easily now.

Best,
Xiao

2022-03-18 15:28 UTC, rhaschke commented
Generally this looks good. Please rebase on latest head to resolve conflicts.

2022-03-20 09:49 UTC, rhaschke requested changes
Looks like you screwed everything when merging with HEAD. Please clean up.
My suggestion is to start from scratch, to be honest.

2022-03-20 09:49 UTC, rhaschke commented on config/arm.xacro
> +        <!-- <disable_default_collisions link="${link}_sc" /> -->
Why did you comment this out?

2022-03-20 09:49 UTC, rhaschke commented on config/arm.xacro
> +        <disable_collisions link1="${link}_sc" link2="$(arg arm_id)_link8" reason="Default" /> -->
These were removed upstream.

2022-03-20 09:49 UTC, rhaschke commented on config/hand.xacro
> +        <disable_collisions link1="${finger}" link2="$(arg arm_id)_hand_sc" reason="Default" />
Here is also a superfluous line.

2022-03-21 16:57 UTC, Xiaoyu27 commented
Hi, I redid the pull request here #106 , you can close this pull request.

2022-03-22 15:24 UTC, v4hn commented
> Hi, I redid the pull request here https://github.com/ros-planning/panda_moveit_config/pull/106 , you can close this pull request.

You could have simply force-pushed your git branch for this pull request instead...

2022-03-22 15:24 UTC, closed without merging