Launch files for running panda_moveit_config with TrajOpt planner
ros-planning/panda_moveit_config pull request #29
Opened 2019-05-23 00:20 UTC by ommmid

Added the necessary launch files so we can run panda_moveit_config package with TrajOpt planner. Also added an empty yaml file for trajopt.

Furthermore, applied the necessary changes so that all the planners can be passed to demo.launch with an arg called planner. In this way, we do not need to make extra demo and move_group for each new planner. 
We can just pass the name: demo.launch planner:=trajopt

2019-05-24 21:01 UTC, davetcoleman requested changes
I'm not sure we should merge this file until trajopt actually exists in moveit. Otherwise users will get confused by the missing functionality.

2019-05-24 21:01 UTC, davetcoleman commented on .setup_assistant
> -moveit_setup_assistant_config:
please restore this file, should not be deleted.

2019-05-24 21:01 UTC, davetcoleman commented on launch/moveit.rviz
>    - Class: rviz/Displays
please restore this file - i don't think these changes are necessary

``git checkout launch/moveit.rviz``

2019-05-24 21:01 UTC, davetcoleman commented on launch/planning_pipeline_trajopt.launch.xml
> +<launch>
i don't think this file is needed, since we have the ``pipeline`` arg. what uses this file?

2019-08-05 14:56 UTC, davetcoleman reviewed
Almost there

2019-08-05 14:56 UTC, davetcoleman commented on config/panda_arm.xacro
> +    <virtual_joint name="virtual_joint" type="fixed" parent_frame="world" child_link="panda_link0" />
why are you changing this? floating is used for things like rviz_visual_tools hiding

2019-08-05 14:56 UTC, davetcoleman commented on launch/demo.launch
> +  <arg name="planner" default="ompl" />
let's keep this change matching whatever is in the setup assistant template. its actually called pipeline there:

https://github.com/ros-planning/moveit/blob/master/moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo.launch#L4

2019-08-05 14:56 UTC, davetcoleman commented on launch/run_benchmark_trajopt.launch
> +  <arg name="cfg" />
is cfg the name Tesseract uses? if not, i'd like to avoid it, since in ros1 it has a common other usage for dynamic reconfigure:
http://wiki.ros.org/dynamic_reconfigure/Tutorials/HowToWriteYourFirstCfgFile

how about trajopt_config ?

2019-08-05 14:56 UTC, davetcoleman commented on launch/run_benchmark_trajopt.launch
> +  <node name="$(anon moveit_benchmark)" pkg="moveit_ros_benchmarks" type="moveit_run_benchmark" args="$(arg cfg) --benchmark-planners" respawn="false" output="screen">
wrap line

2019-08-07 18:43 UTC, ommmid commented on config/panda_arm.xacro
> +    <virtual_joint name="virtual_joint" type="fixed" parent_frame="world" child_link="panda_link0" />
if it is floating, then haveCompletedState() from StateMonitor never returns true Indicating we have no joint state information for at least one joint. I revert this back to floating but open an issue. It is the same problem in #33 but I am running melodic

2019-08-07 20:52 UTC, davetcoleman commented on config/panda_arm.xacro
> +    <virtual_joint name="virtual_joint" type="fixed" parent_frame="world" child_link="panda_link0" />
Got it. We can leave it as fixed. It will make "hiding" a robot hard, but I've created a PR and some issues to track this needed fix in the future: https://github.com/ros-planning/moveit_msgs/pull/55

2019-08-07 20:53 UTC, davetcoleman approved these changes
Great!

2019-08-07 20:53 UTC, merged