Create a yaml for joint weights
ros-planning/panda_moveit_config pull request #45
Opened 2019-11-21 00:03 UTC by gonfreces

- [ ] Create a joint weights yaml to set the scaling factor for the distance metrics of the manipulators
- [ ] This pull request will help in checking the pull request for the moveit repository which adds a feature for scaling the distance metrics for the manipulators #1758

2019-11-21 00:05 UTC, mamoll commented on config/joint_weights.yaml
> +joint_weights:
Why not simply write the list like so:

```
joint_weights:
   panda_joint1: 0.5
   panda_joint2: 0.5
   ...
```

2019-11-21 00:16 UTC, gonfreces commented on config/joint_weights.yaml
> +joint_weights:
I have made it similar to the joint_limits.yaml i.e, to use the same variable for different joints. In the robot_model_loader.cpp it becomes easier to assign the same variable to distance factors of different joints. So it's independent of joint names as we already have an object pointing to the different joints.

2019-11-21 08:03 UTC, rhaschke requested changes
I agree to @mamoll: `joint_limits.yaml` defines several variables per joint. However, here only a single weight is defined. Hence, please change to the syntax proposed by Mark.

2019-11-22 16:49 UTC, v4hn commented
This requests depends on the outcome of https://github.com/ros-planning/moveit/issues/1446

2019-11-30 09:34 UTC, GabrielKoenig commented
Please take a look at my thoughs in https://github.com/ros-planning/moveit/issues/1446#issuecomment-559934674 before merging....

2022-09-01 12:16 UTC, closed without merging