fix initial state of robot
ros-planning/panda_moveit_config pull request #47
Opened 2019-11-26 11:39 UTC by rhaschke

Fixes https://github.com/ros-planning/moveit/pull/1780#issuecomment-558587911 by removing _arm_ group states from `panda_arm_hand` JMG. Defining an arm state only make sense for the arm group.

2019-11-26 12:22 UTC, henningkayser requested changes

2019-11-26 12:22 UTC, henningkayser commented on config/panda_arm_hand.srdf.xacro
> -  <!--GROUP STATES: Purpose: Define a named state for a particular group, in terms of joint values. This is useful to define states like 'folded arms'-->
These should be assigned to group `panda_arm` and not be removed.

2019-11-26 12:29 UTC, rhaschke commented on config/panda_arm_hand.srdf.xacro
> -  <!--GROUP STATES: Purpose: Define a named state for a particular group, in terms of joint values. This is useful to define states like 'folded arms'-->
They "are" still available in 
https://github.com/ros-planning/panda_moveit_config/blob/4a16a4fcdbf5cc7975937faa1b0ebcf8d41b365d/config/panda_arm.xacro#L13-L21
However, you are right `extended` is not defined there. I don't have time to fix this now. Please feel free to do so :smile:

2019-11-26 16:09 UTC, rhaschke commented on config/panda_arm_hand.srdf.xacro
> -  <!--GROUP STATES: Purpose: Define a named state for a particular group, in terms of joint values. This is useful to define states like 'folded arms'-->
Done now.

2019-11-28 10:03 UTC, JafarAbdi approved these changes

2019-12-11 00:43 UTC, henningkayser commented on config/panda_arm.xacro
> +    <group_state name="extended" group="panda_arm_hand">
Correct me if I'm wrong, but don't we want `group="panda_arm"` just like with the `ready` pose?

2019-12-11 09:45 UTC, rhaschke commented on config/panda_arm.xacro
> +    <group_state name="extended" group="panda_arm_hand">
Good catch: a classical cut-and-paste error. Fixed now.

2020-02-05 13:10 UTC, merged