including planners from melodic branch; add named group_state in panda_arm_hand srdf
ros-planning/panda_moveit_config pull request #48
Opened 2019-11-27 20:01 UTC by justagist

2019-11-27 20:16 UTC, rhaschke reviewed
Please consider #47 and base your PR on top of that.

2019-11-27 20:16 UTC, rhaschke commented on config/panda_arm_hand.srdf.xacro
> +  <group_state name="extended" group="panda_arm_hand">
The `extented` state should be added to `panda_arm.xacro`. See pending PR #47.

2019-11-27 20:37 UTC, justagist commented on config/panda_arm_hand.srdf.xacro
> +  <group_state name="extended" group="panda_arm_hand">
I've done that now!

2019-11-28 07:21 UTC, rhaschke requested changes
Please completely remove the `ready` group from `panda_arm_hand` group in `panda_arm_hand.srdf.xacro`.

2019-11-28 09:00 UTC, justagist commented
The `ready` group in `panda_arm_hand` has joints from both the arm and gripper. I left it there as a state for the combined group `panda_arm_hand`.

2019-12-06 07:31 UTC, rhaschke requested changes
I think we should unify the kinetic and melodic branch versions. Why did you introduce new values for the `extended` state? What is more meaningful about those values? Please explain.

2019-12-06 07:31 UTC, rhaschke commented on config/panda_arm_hand.srdf.xacro
> +    <joint name="panda_finger_joint1" value="0.035" />
Instead of extending and duplicating the `ready` pose here, you should update `fake_controllers.yaml` to include another initial pose for the hand group.
https://github.com/ros-planning/panda_moveit_config/blob/4a16a4fcdbf5cc7975937faa1b0ebcf8d41b365d/config/fake_controllers.yaml#L15-L17

2019-12-11 00:46 UTC, henningkayser reviewed
@justagist Why should the melodic planner configs (TrajOpt) be added to the kinetic branch?

> I think we should unify the kinetic and melodic branch versions. Why did you introduce new values for the `extended` state? What is more meaningful about those values? Please explain.

@rhaschke In general I agree. I'm just afraid we would have to maintain a superset of configurations that works for both versions.

2019-12-11 00:58 UTC, justagist commented on config/panda_arm_hand.srdf.xacro
> +    <joint name="panda_finger_joint1" value="0.035" />
I use the `ready` pose of the extended group to plan and execute trajectory for the robot to the ready pose and the gripper to the open configuration simultaneously.

2019-12-11 01:00 UTC, justagist commented on config/panda_arm_hand.srdf.xacro
> +    <joint name="panda_finger_joint1" value="0.035" />
I thought it would be useful to have it there.

2019-12-11 10:11 UTC, rhaschke commented
Indeed, adding TrajOpt to Kinetic doesn't make sense as TrajOpt is not available in MoveIt Kinetic.

2019-12-11 10:21 UTC, justagist commented
That is true; I hadn't checked the planner config when I merged from melodic branch, sorry about that. I have removed it now.

2020-02-05 13:40 UTC, rhaschke commented
Replaced with #52.

2020-02-05 13:40 UTC, closed without merging