Restructure controller managers
ros-planning/panda_moveit_config pull request #92
Opened 2021-10-24 17:55 UTC by rhaschke

There are 3 basic MoveIt controller manager plugins:
- `fake` = `moveit_fake_controller_manager/MoveItFakeControllerManager`
  Used in `demo.launch`. Doesn't really control the robot, but just interpolates between via points. Allows these `execution_types`:
  - `via points`: just jumps to the via points
  - `interpolate`: linearly interpolates between via points (default)
  - `last point`: jumps to the final trajectory point (used for fast execution testing)

- `ros_control` = `moveit_ros_control_interface::MoveItControllerManager`
  Interfaces to `ros_control` controllers.
  The package [`moveit_sim_controller`](https://github.com/PickNikRobotics/moveit_sim_controller) offers a fake controller complying to the ros_control API.

- `simple` = `moveit_simple_controller_manager/MoveItSimpleControllerManager`
  Interfaces to action servers for `FollowJointTrajectory` and/or `GripperCommand` that in turn interface to the low-level robot controllers

However, so far `move_group.launch` distinguished between `fake` and `robot` mode only.
My suggestion is to introduce the argument `moveit_controller_manager` allowing all 3 variants.

I suggest adapting MSA templates appropriately as well. What do you think, @v4hn, @rickstaa?

2021-10-25 08:33 UTC, rickstaa commented
@rhaschke Good idea. Giving users the ability to switch between these three controllers is important since the `moveit_fake_controller_manager` is being replaced with the [moveit_sim_controller](https://github.com/PickNikRobotics/moveit_sim_controller). I think a great number of users already switched. Further, we already did add the configuration values for the `moveit_sim_controller` to both the MSA and the `panda_moveit_config`:

https://github.com/ros-planning/panda_moveit_config/blob/5847d2bbe138e1a502ec098d3428a247b892afce/config/ros_controllers.yaml#L1-L4

I think applying your changes to both the `panda_moveit_config` and the MSA is a good idea.

2021-10-25 09:48 UTC, rickstaa requested changes

2021-10-25 09:48 UTC, rickstaa commented on config/ros_controllers.yaml
> +  type: effort_controllers/JointTrajectoryController
@rhaschke Why did you switch back to using an `effort_controllers/JointTrajectoryController`? 

Last week, I tested the old melodic-devel PID gains and the new PID gains provided by @gollth (see https://github.com/frankaemika/franka_ros/issues/161#issuecomment-930173703) from @frankaemika on the real robot. While doing so I found out although both work in the simulation they do not work on the real robot:
- The gains that we used in the `melodic-devel` branch are to high leading to dangerous velocities when the controllers are started. 
- The new gains are stable but more than often lead to MoveIt running into a timeout probably since they don't have a integral term.

For this reason, I switched to using the `position_controllers/JointTrajectoryController` that is provided (see https://github.com/frankaemika/franka_ros/blob/da13eb1d6f5cc9600dbb22a60759016e715e8d27/franka_control/config/default_controllers.yaml#L1-L26). This controller works both on the real robot and in simulation and doesn't require us to tune PID gains (for the simulation https://github.com/frankaemika/franka_ros/pull/181 is needed).

2021-10-25 09:48 UTC, rickstaa commented on config/moveit_sim_controller.yaml
> +  type: velocity_controllers/JointTrajectoryController
Why do you use a velocity_controller while we, in the `franka_gazebo.launch` file, request the `hardware_interface/PositionJointInterface` hardware interface?

https://github.com/ros-planning/panda_moveit_config/blob/d2b09ea4722414f5e7e97093dfa5f790a56207b2/launch/franka_gazebo.launch#L26

Maybe this is because of something related to the [moveit_sim_controller](https://github.com/PickNikRobotics/moveit_sim_controller) which I'm unaware of?

2021-10-25 09:48 UTC, rickstaa commented on launch/moveit_sim_controller.launch
> +<launch>
It could be that I am missing something but I could not find where this launch is used. Maybe also related to how the [moveit_sim_controller](https://github.com/PickNikRobotics/moveit_sim_controller) works?

2021-10-25 09:52 UTC, rickstaa commented
@rhaschke I'm currently not at the university so I can not test the `panda_control_moveit_rviz.launch` file. Based on your changes I however do not expect any issues other than the PID gains being poorly tuned (see my comments). I tested the `demo.launch` file and I found no problems. I however was not able to control the simulated robot when using the `franka_gazebo.launch` file. When trying to use the gazebo simulation I receive the following error:

```bash
[/panda/move_group] [ WARN] [WallTime: 1635155355.357972037, 62.387000000]: Failed to read controllers from /controller_manager/list_controllers
[/panda/move_group] [ERROR] [WallTime: 1635155355.358041334, 62.387000000]: Unable to identify any set of controllers that can actuate the specified joints: [ panda_joint1 panda_joint2 panda_joint3 panda_joint4 panda_joint5 panda_joint6 panda_joint7 ]
[/panda/move_group] [ERROR] [WallTime: 1635155355.358076436, 62.387000000]: Known controllers and their joints:

[/panda/move_group] [ERROR] [WallTime: 1635155355.358121636, 62.387000000]: Apparently trajectory initialization failed
```

I did not debug this issue yet but it looks like the `controllers_list` parameter is not loaded (also see my comments).

2021-10-25 10:11 UTC, rhaschke commented on config/ros_controllers.yaml
> +  type: effort_controllers/JointTrajectoryController
I would expect that we need to use different gains for sim and real.

2021-10-25 10:13 UTC, rhaschke commented on config/moveit_sim_controller.yaml
> +  type: velocity_controllers/JointTrajectoryController
`moveit_sim_controller` doesn't need Gazebo or isn't related to Gazebo in any fashion.
It's just a fake controller using the `ros_control` API.

2021-10-25 10:15 UTC, rhaschke commented on launch/moveit_sim_controller.launch
> +<launch>
As stated in the corresponding commit message, this needs to be explicitly launched:
```bash
roslaunch panda_moveit_config demo.launch moveit_controller_manager:=ros_control
roslaunch panda_moveit_config moveit_sim_controller.launch
```

2021-10-25 10:22 UTC, rickstaa commented on config/moveit_sim_controller.yaml
> +  type: velocity_controllers/JointTrajectoryController
@rhaschke Ah sorry for that I'm not familiar with the [moveit_sim_controller](https://github.com/PickNikRobotics/moveit_sim_controller) package. I now see how it is being used.

2021-10-25 10:30 UTC, rickstaa commented on launch/moveit_sim_controller.launch
> +<launch>
Ah sorry for that. I will check the commit messages next time. 

In that case, the code looks good to me. I however can not test it since the [moveit_sim_controller](https://github.com/PickNikRobotics/moveit_sim_controller) package is not yet released for ROS noetic and the melodic-branch does not build with ROS noetic.

2021-10-25 10:33 UTC, rickstaa commented on launch/moveit_sim_controller.launch
> +<launch>
Is there a reason why you did not include the `moveit_sim_controller.launch` file inside the `ros_control_moveit_controller_manager.launch.xml` launch file?

2021-10-25 10:37 UTC, rickstaa commented on config/ros_controllers.yaml
> +  type: effort_controllers/JointTrajectoryController
@rhaschke You are right. I would also be surprised if the sim and real robot work with the same gains. I, however, did not yet find working gains for the `effort_controllers/JointTrajectoryController` controller on the real robot. I did not spend much time trying to tune this controller since the `position_controllers/JointTrajectoryController` controller worked. 

Is there a reason you want to use the `effort_controllers/JointTrajectoryController` over the `position_controllers/JointTrajectoryController` when working with the real robot?

2021-10-25 10:39 UTC, rickstaa commented on launch/moveit_sim_controller.launch
> +<launch>
Ah, I think I understand it is because you also use the `ros_control_moveit_controller_manager.launch.xml` for the `franka_gazebo` simulation. 

Feel free to answer my questions in our discussion later.

2021-10-25 16:08 UTC, rickstaa commented
@rhaschke As we discussed in our call, https://github.com/rhaschke/panda_moveit_config/pull/11 splits the controller config file between the real and simulated robot.

I converted it to a draft as it was a first attempt to get both the real and simulated robot to work with the `moveit_ros_control_interface`. The current version solves the warning above but could be improved as it clutters the codebase.

2021-10-25 19:06 UTC, rhaschke commented on launch/moveit_sim_controller.launch
> +<launch>
`ros_control_moveit_controller_manager.launch.xml` just prepares MoveIt for `ros_control` use.
Then we have multiple options to actually spawn `ros_control` controllers:
- `moveit_sim_controller.launch`
- `ros_controllers.launch` used by `panda_moveit.launch` and `demo_gazebo.launch`
- `franka_gazebo.launch`

2021-10-25 19:08 UTC, rickstaa commented on launch/moveit_sim_controller.launch
> +<launch>
@rhaschke Ah, that makes sense! Thanks for the explanation.

2021-10-25 19:08 UTC, rickstaa approved these changes

2021-10-25 19:11 UTC, rickstaa commented
@rhaschke Please let me know when I need to reserve a lab slot to quickly test it on the real robot.

2021-11-08 08:38 UTC, closed without merging

2021-11-08 08:40 UTC, rhaschke commented
Superseded by new `noetic-devel` branch.